(define (make-body) (let ((v-list (list 1 2 3)))
(define (change-list-to! l) (set! v-list l))
(define (dis-list) (display v-list))
(define (dispach command)
(cond ((eq? command 's!)
change-list-to!)
((eq? command 'd)
dis-list)
(else 'error)))
dispach))
